name: my_portfolio
description: "mpm website."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  url_launcher: ^6.3.0
  visibility_detector: ^0.4.0+1
  timeline_tile: ^2.0.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # Add this line to include the whole folder
    - assets/fonts/
    - assets/icon/
    - assets/Mohammad-Parsa-Malek-Resume.pdf
  fonts:
    - family: Parisienne
      fonts:
        - asset: assets/fonts/Parisienne-Regular.ttf
flutter_launcher_icons:
  image_path: "assets/icon/MPM.png" # <--- IMPORTANT: This is the path to your new icon
  web:
    generate: true
    image_path: "assets/icon/MPM.png" # <--- IMPORTANT: Path for web icons
